franka_state_controller:
  type: franka_control/FrankaStateController
  publish_rate: 30  # [Hz]
  arm_id: $(arg arm_id)
  joint_names:
    - $(arg arm_id)_joint1
    - $(arg arm_id)_joint2
    - $(arg arm_id)_joint3
    - $(arg arm_id)_joint4
    - $(arg arm_id)_joint5
    - $(arg arm_id)_joint6
    - $(arg arm_id)_joint7

model_example_controller:
  type: franka_example_controllers/ModelExampleController
  arm_id: $(arg arm_id)

force_example_controller:
  type: franka_example_controllers/ForceExampleController
  arm_id: $(arg arm_id)
  joint_names:
    - $(arg arm_id)_joint1
    - $(arg arm_id)_joint2
    - $(arg arm_id)_joint3
    - $(arg arm_id)_joint4
    - $(arg arm_id)_joint5
    - $(arg arm_id)_joint6
    - $(arg arm_id)_joint7

cartesian_impedance_example_controller:
  type: franka_example_controllers/CartesianImpedanceExampleController
  arm_id: $(arg arm_id)
  joint_names:
    - $(arg arm_id)_joint1
    - $(arg arm_id)_joint2
    - $(arg arm_id)_joint3
    - $(arg arm_id)_joint4
    - $(arg arm_id)_joint5
    - $(arg arm_id)_joint6
    - $(arg arm_id)_joint7


kth_cartesian_velocity_effort_interface_controller:
    type: franka_example_controllers/KthCartesianVelocityEffortInterfaceController    
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Kp: 
        - 400 
        - 400 
        - 400 
        - 30 
        - 30 
        - 30 
    impedance: 1     
    static: 1    
    Kpos: 250.0
    Kor: 150.0
    Mdpos: 1.0
    Mdor: 1.0
    

kth_cartesian_pose_effort_interface_controller:
    type: franka_example_controllers/KthCartesianPoseEffortInterfaceController    
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Kp: 
        - 400 
        - 400 
        - 400 
        - 30 
        - 30 
        - 30 
    impedance: 1     
    static: 1    
    Kpos: 250.0
    Kor: 150.0
    Mdpos: 1.0
    Mdor: 1.0

kth_joint_pose_effort_interface_controller:
    type: franka_example_controllers/KthJointPoseEffortInterfaceController    
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Kp: 
        - 400 
        - 400 
        - 400 
        - 30 
        - 30 
        - 30 
    impedance: 1     
    static: 1    
    Kpos: 250.0
    Kor: 150.0
    Mdpos: 1.0
    Mdor: 1.0

kth_joint_velocity_effort_interface_controller:
    type: franka_example_controllers/KthJointVelocityEffortInterfaceController    
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Kp: 
        - 400 
        - 400 
        - 400 
        - 30 
        - 30 
        - 30 
    impedance: 1     
    static: 1    
    Kpos: 250.0
    Kor: 150.0
    Mdpos: 1.0
    Mdor: 1.0


dual_arm_cartesian_impedance_example_controller:
    type: franka_example_controllers/DualArmCartesianImpedanceExampleController
    right:
        arm_id: $(arg arm_id)
        joint_names:
            - $(arg arm_id)_joint1
            - $(arg arm_id)_joint2
            - $(arg arm_id)_joint3
            - $(arg arm_id)_joint4
            - $(arg arm_id)_joint5
            - $(arg arm_id)_joint6
            - $(arg arm_id)_joint7
    left:
        arm_id: $(arg arm_id)
        joint_names:
            - $(arg arm_id)_joint1
            - $(arg arm_id)_joint2
            - $(arg arm_id)_joint3
            - $(arg arm_id)_joint4
            - $(arg arm_id)_joint5
            - $(arg arm_id)_joint6
            - $(arg arm_id)_joint7


dual_arm_dressing_controller:
    type: franka_example_controllers/DualArmDressingController
    left:
        arm_id: $(arg arm_id)
        joint_names:
            - $(arg arm_id)_joint1
            - $(arg arm_id)_joint2
            - $(arg arm_id)_joint3
            - $(arg arm_id)_joint4
            - $(arg arm_id)_joint5
            - $(arg arm_id)_joint6
            - $(arg arm_id)_joint7
        Kp: 
            - 400 
            - 400 
            - 400 
            - 30 
            - 30 
            - 30 
        impedance: 1     
        static: 1
    right:
        arm_id: $(arg arm_id)
        joint_names:
            - $(arg arm_id)_joint1
            - $(arg arm_id)_joint2
            - $(arg arm_id)_joint3
            - $(arg arm_id)_joint4
            - $(arg arm_id)_joint5
            - $(arg arm_id)_joint6
            - $(arg arm_id)_joint7
        Kp: 
            - 400 
            - 400 
            - 400 
            - 30 
            - 30 
            - 30 
        impedance: 1     
        static: 1
    Kpos: 250.0
    Kor: 150.0
    Mdpos: 1.0
    Mdor: 1.0

